[project]
name = "fastapiproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi>=0.128.0",
    "passlib>=1.7.4",
    "scrypt>=0.9.4",
    "sqlalchemy>=2.0.45",
    "uvicorn>=0.40.0",
]
